title: Your awesome title
author: Wadinga Leonard
email: info@wadingaleonard.me
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my blog, here you will be able to read and follow all posts I create under the various categories listed below. So stay tuned for the best, thanks.

# social links
twitter_username: @wleo37
github_username:  wadleo

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
